<?xml version="1.0" encoding="UTF-8"?>
<itsgml:FC_FeatureCatalogue xmlns:gml="http://www.opengis.net/gml/3.2"
    xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmx="http://www.isotc211.org/2005/gmx"
    xmlns:gsr="http://www.isotc211.org/2005/gsr" xmlns:gts="http://www.isotc211.org/2005/gts"
    xmlns:gss="http://www.isotc211.org/2005/gss" xmlns:gmlexr="http://www.opengis.net/gml/3.3/exr"
    xmlns:itsgml="https://raw.githubusercontent.com/jetgeo/ITSGML/master/XSD"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://raw.githubusercontent.com/jetgeo/ITSGML/master/XSD file:/C:/DATA/GitHub/ITSGML/XSD/itsfcm.xsd">
    <gmx:name>
        <gco:CharacterString>INSPIRE TN</gco:CharacterString>
    </gmx:name>
    <gmx:scope>
        <gco:CharacterString>Infrastructure of spatial information in Europe</gco:CharacterString>
    </gmx:scope>
    <gmx:versionNumber>
        <gco:CharacterString>prototype</gco:CharacterString>
    </gmx:versionNumber>
    <gmx:versionDate>
        <gco:Date>2018-10-29</gco:Date>
    </gmx:versionDate>
    <itsgml:producer/>
    <itsgml:globalProperty>
        <itsgml:FC_FeatureAttribute gml:id="inspire.id">
            <itsgml:memberName>inspireId</itsgml:memberName>
            <itsgml:cardinality>
                <gco:Multiplicity>
                    <gco:range>
                        <gco:MultiplicityRange>
                            <gco:lower>
                                <gco:Integer>0</gco:Integer>
                            </gco:lower>
                            <gco:upper>
                                <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                            </gco:upper>
                        </gco:MultiplicityRange>
                    </gco:range>
                </gco:Multiplicity>
            </itsgml:cardinality>
            <itsgml:subattribute>
                <itsgml:FC_FeatureAttribute>
                    <itsgml:memberName>localId</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                    <itsgml:valueType>CharacterString</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:subattribute>
            <itsgml:subattribute>
                <itsgml:FC_FeatureAttribute>
                    <itsgml:memberName>namespace</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                    <itsgml:valueType>CharacterString</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:subattribute>
            <itsgml:subattribute>
                <itsgml:FC_FeatureAttribute>
                    <itsgml:memberName>versionId</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>0</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                    <itsgml:valueType>CharacterString</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:subattribute>
        </itsgml:FC_FeatureAttribute>
    </itsgml:globalProperty>
    <itsgml:globalProperty>
        <itsgml:FC_FeatureAttribute gml:id="inspire.nr">
            <itsgml:memberName>inspireId</itsgml:memberName>
            <itsgml:cardinality>
                <gco:Multiplicity>
                    <gco:range>
                        <gco:MultiplicityRange>
                            <gco:lower>
                                <gco:Integer>0</gco:Integer>
                            </gco:lower>
                            <gco:upper>
                                <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                            </gco:upper>
                        </gco:MultiplicityRange>
                    </gco:range>
                </gco:Multiplicity>
            </itsgml:cardinality>
            <itsgml:subattribute>
                <itsgml:FC_FeatureAttribute>
                    <itsgml:memberName>localId</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                    <itsgml:valueType>CharacterString</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:subattribute>
            <itsgml:subattribute>
                <itsgml:FC_FeatureAttribute>
                    <itsgml:memberName>namespace</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                    <itsgml:valueType>CharacterString</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:subattribute>
            <itsgml:subattribute>
                <itsgml:FC_FeatureAttribute>
                    <itsgml:memberName>versionId</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>0</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                    <itsgml:valueType>CharacterString</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:subattribute>
        </itsgml:FC_FeatureAttribute>
    </itsgml:globalProperty>
    <itsgml:featureType>
        <itsgml:FC_FeatureType gml:id="inspire.np">
            <itsgml:typeName>NetworkProperty</itsgml:typeName>
            <itsgml:isAbstract>true</itsgml:isAbstract>
            <itsgml:carrierOfCharacteristics xlink:href="fc_inspire.gml#inspire.id"/>
        </itsgml:FC_FeatureType>
    </itsgml:featureType>
    <itsgml:featureType>
        <itsgml:FC_FeatureType gml:id="inspire.tn.tp">
            <itsgml:typeName>TransportProperty</itsgml:typeName>
            <itsgml:isAbstract>true</itsgml:isAbstract>
            <itsgml:inheritsFrom xlink:href="fc_inspire.gml#inspire.np"/>
        </itsgml:FC_FeatureType>
    </itsgml:featureType>
    <itsgml:featureType>
        <itsgml:FC_FeatureType gml:id="inspire.tn.rd.sl">
            <itsgml:typeName>SpeedLimit</itsgml:typeName>
            <itsgml:isAbstract>false</itsgml:isAbstract>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute>
                    <itsgml:memberName>speedLimitMinMaxType</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                    <itsgml:listedValue>
                        <itsgml:FC_ListedValue>
                            <itsgml:label>maximum</itsgml:label>
                        </itsgml:FC_ListedValue>
                    </itsgml:listedValue>
                    <itsgml:listedValue>
                        <itsgml:FC_ListedValue>
                            <itsgml:label>minimum</itsgml:label>
                        </itsgml:FC_ListedValue>
                    </itsgml:listedValue>
                    <itsgml:listedValue>
                        <itsgml:FC_ListedValue>
                            <itsgml:label>recomendedMaximum</itsgml:label>
                        </itsgml:FC_ListedValue>
                    </itsgml:listedValue>
                    <itsgml:listedValue>
                        <itsgml:FC_ListedValue>
                            <itsgml:label>recomendedMinimum</itsgml:label>
                        </itsgml:FC_ListedValue>
                    </itsgml:listedValue>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute>
                    <itsgml:memberName>speedLimitValue</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                    <itsgml:valueMeasurementUnit uom="Kmph"/>
                    <itsgml:valueType>Integer</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:inheritsFrom xlink:href="fc_inspire.gml#inspire.tn.tp"/>
        </itsgml:FC_FeatureType>
    </itsgml:featureType>
    <itsgml:featureType>
        <itsgml:FC_FeatureType gml:id="inspire.tn.rd.rw">
            <itsgml:typeName>RoadWidth</itsgml:typeName>
            <itsgml:isAbstract>false</itsgml:isAbstract>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute>
                    <itsgml:memberName>width</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                    <itsgml:valueMeasurementUnit uom="Metre"/>
                    <itsgml:valueType>Real</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
        </itsgml:FC_FeatureType>
    </itsgml:featureType>
    <itsgml:featureType>
        <itsgml:FC_FeatureType gml:id="inspire.tn.rn.frc">
            <itsgml:typeName>FunctionalRoadClass</itsgml:typeName>
            <itsgml:isAbstract>false</itsgml:isAbstract>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute>
                    <itsgml:memberName>functionalClass</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                    <itsgml:listedValue>
                        <itsgml:FC_ListedValue>
                            <itsgml:label>mainRoad</itsgml:label>
                        </itsgml:FC_ListedValue>
                    </itsgml:listedValue>
                    <itsgml:listedValue>
                        <itsgml:FC_ListedValue>
                            <itsgml:label>firstClass</itsgml:label>
                        </itsgml:FC_ListedValue>
                    </itsgml:listedValue>
                    <itsgml:listedValue>
                        <itsgml:FC_ListedValue>
                            <itsgml:label>secondClass</itsgml:label>
                        </itsgml:FC_ListedValue>
                    </itsgml:listedValue>
                    <itsgml:listedValue>
                        <itsgml:FC_ListedValue>
                            <itsgml:label>thirdClass</itsgml:label>
                        </itsgml:FC_ListedValue>
                    </itsgml:listedValue>
                    <itsgml:listedValue>
                        <itsgml:FC_ListedValue>
                            <itsgml:label>fourthClass</itsgml:label>
                        </itsgml:FC_ListedValue>
                    </itsgml:listedValue>
                    <itsgml:listedValue>
                        <itsgml:FC_ListedValue>
                            <itsgml:label>fifthClass</itsgml:label>
                        </itsgml:FC_ListedValue>
                    </itsgml:listedValue>
                    <itsgml:listedValue>
                        <itsgml:FC_ListedValue>
                            <itsgml:label>sixthClass</itsgml:label>
                        </itsgml:FC_ListedValue>
                    </itsgml:listedValue>
                    <itsgml:listedValue>
                        <itsgml:FC_ListedValue>
                            <itsgml:label>seventhClass</itsgml:label>
                        </itsgml:FC_ListedValue>
                    </itsgml:listedValue>
                    <itsgml:listedValue>
                        <itsgml:FC_ListedValue>
                            <itsgml:label>eigthClass</itsgml:label>
                        </itsgml:FC_ListedValue>
                    </itsgml:listedValue>
                    <itsgml:listedValue>
                        <itsgml:FC_ListedValue>
                            <itsgml:label>ninthClass</itsgml:label>
                        </itsgml:FC_ListedValue>
                    </itsgml:listedValue>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
        </itsgml:FC_FeatureType>
    </itsgml:featureType>
</itsgml:FC_FeatureCatalogue>
