<itsgml:FC_FeatureCatalogue xmlns:xlink="http://www.w3.org/1999/xlink"
 xmlns:gco="http://www.isotc211.org/2005/gco"
 xmlns:gmx="http://www.isotc211.org/2005/gmx"
 xmlns:gml="http://www.opengis.net/gml/3.2"
 xmlns:gmd="http://www.isotc211.org/2005/gmd"
 xmlns:gss="http://www.isotc211.org/2005/gss"
 xmlns:gmlexr="http://www.opengis.net/gml/3.3/exr"
 xmlns:itsgml="https://raw.githubusercontent.com/jetgeo/ITSGML/master/XSD"
 xmlns:gts="http://www.isotc211.org/2005/gts"
 xmlns:gsr="http://www.isotc211.org/2005/gsr"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://raw.githubusercontent.com/jetgeo/ITSGML/master/XSD https://raw.githubusercontent.com/jetgeo/ITSGML/master/XSD/itsfcm.xsd">
    <gmx:name>
        <gco:CharacterString>INSPIRE_TN</gco:CharacterString>
    </gmx:name>
    <gmx:scope>
        <gco:CharacterString>INSPIRE Transport Network Feature Catalogue</gco:CharacterString>
    </gmx:scope>
    <gmx:versionNumber>
        <gco:CharacterString>Prototype</gco:CharacterString>
    </gmx:versionNumber>
    <gmx:versionDate>
        <gco:Date>2018-12-13</gco:Date>
    </gmx:versionDate>
    <itsgml:producer>
        <gco:CharacterString>INSPIRE</gco:CharacterString>
    </itsgml:producer>
    <itsgml:valueDomain>
        <itsgml:FC_ValueDomain gml:id="INSPIRE_TN.LinkDirectionValue">
            <itsgml:typeName>LinkDirectionValue</itsgml:typeName>
            <itsgml:listedValue>
                <itsgml:FC_ListedValue gml:id="INSPIRE_TN.LinkDirectionValue.bothDirections">
                    <itsgml:label>bothDirections</itsgml:label>
                </itsgml:FC_ListedValue>
            </itsgml:listedValue>
            <itsgml:listedValue>
                <itsgml:FC_ListedValue gml:id="INSPIRE_TN.LinkDirectionValue.inDirection">
                    <itsgml:label>inDirection</itsgml:label>
                </itsgml:FC_ListedValue>
            </itsgml:listedValue>
            <itsgml:listedValue>
                <itsgml:FC_ListedValue gml:id="INSPIRE_TN.LinkDirectionValue.inOppositeDirection">
                    <itsgml:label>inOppositeDirection</itsgml:label>
                </itsgml:FC_ListedValue>
            </itsgml:listedValue>
        </itsgml:FC_ValueDomain>
    </itsgml:valueDomain>
    <itsgml:valueDomain>
        <itsgml:FC_ValueDomain gml:id="INSPIRE_TN.SpeedLimitMinMaxValue">
            <itsgml:typeName>SpeedLimitMinMaxValue</itsgml:typeName>
            <itsgml:listedValue>
                <itsgml:FC_ListedValue gml:id="INSPIRE_TN.SpeedLimitMinMaxValue.maximum">
                    <itsgml:label>maximum</itsgml:label>
                </itsgml:FC_ListedValue>
            </itsgml:listedValue>
            <itsgml:listedValue>
                <itsgml:FC_ListedValue gml:id="INSPIRE_TN.SpeedLimitMinMaxValue.minimum">
                    <itsgml:label>minimum</itsgml:label>
                </itsgml:FC_ListedValue>
            </itsgml:listedValue>
            <itsgml:listedValue>
                <itsgml:FC_ListedValue gml:id="INSPIRE_TN.SpeedLimitMinMaxValue.recommendedMaximum">
                    <itsgml:label>recommendedMaximum</itsgml:label>
                </itsgml:FC_ListedValue>
            </itsgml:listedValue>
            <itsgml:listedValue>
                <itsgml:FC_ListedValue gml:id="INSPIRE_TN.SpeedLimitMinMaxValue.recommendedMinimum">
                    <itsgml:label>recommendedMinimum</itsgml:label>
                </itsgml:FC_ListedValue>
            </itsgml:listedValue>
        </itsgml:FC_ValueDomain>
    </itsgml:valueDomain>
    <itsgml:valueDomain>
        <itsgml:FC_ValueDomain gml:id="INSPIRE_TN.FunctionalRoadClassValue">
            <itsgml:typeName>FunctionalRoadClassValue</itsgml:typeName>
            <itsgml:listedValue>
                <itsgml:FC_ListedValue gml:id="INSPIRE_TN.FunctionalRoadClassValue.mainRoad">
                    <itsgml:label>mainRoad</itsgml:label>
                </itsgml:FC_ListedValue>
            </itsgml:listedValue>
            <itsgml:listedValue>
                <itsgml:FC_ListedValue gml:id="INSPIRE_TN.FunctionalRoadClassValue.firstClass">
                    <itsgml:label>firstClass</itsgml:label>
                </itsgml:FC_ListedValue>
            </itsgml:listedValue>
            <itsgml:listedValue>
                <itsgml:FC_ListedValue gml:id="INSPIRE_TN.FunctionalRoadClassValue.secondClass">
                    <itsgml:label>secondClass</itsgml:label>
                </itsgml:FC_ListedValue>
            </itsgml:listedValue>
            <itsgml:listedValue>
                <itsgml:FC_ListedValue gml:id="INSPIRE_TN.FunctionalRoadClassValue.thirdClass">
                    <itsgml:label>thirdClass</itsgml:label>
                </itsgml:FC_ListedValue>
            </itsgml:listedValue>
            <itsgml:listedValue>
                <itsgml:FC_ListedValue gml:id="INSPIRE_TN.FunctionalRoadClassValue.fourthClass">
                    <itsgml:label>fourthClass</itsgml:label>
                </itsgml:FC_ListedValue>
            </itsgml:listedValue>
            <itsgml:listedValue>
                <itsgml:FC_ListedValue gml:id="INSPIRE_TN.FunctionalRoadClassValue.fifthClass">
                    <itsgml:label>fifthClass</itsgml:label>
                </itsgml:FC_ListedValue>
            </itsgml:listedValue>
            <itsgml:listedValue>
                <itsgml:FC_ListedValue gml:id="INSPIRE_TN.FunctionalRoadClassValue.sixthClass">
                    <itsgml:label>sixthClass</itsgml:label>
                </itsgml:FC_ListedValue>
            </itsgml:listedValue>
            <itsgml:listedValue>
                <itsgml:FC_ListedValue gml:id="INSPIRE_TN.FunctionalRoadClassValue.seventhClass">
                    <itsgml:label>seventhClass</itsgml:label>
                </itsgml:FC_ListedValue>
            </itsgml:listedValue>
            <itsgml:listedValue>
                <itsgml:FC_ListedValue gml:id="INSPIRE_TN.FunctionalRoadClassValue.eighthClass">
                    <itsgml:label>eighthClass</itsgml:label>
                </itsgml:FC_ListedValue>
            </itsgml:listedValue>
            <itsgml:listedValue>
                <itsgml:FC_ListedValue gml:id="INSPIRE_TN.FunctionalRoadClassValue.ninthClass">
                    <itsgml:label>ninthClass</itsgml:label>
                </itsgml:FC_ListedValue>
            </itsgml:listedValue>
        </itsgml:FC_ValueDomain>
    </itsgml:valueDomain>
    <itsgml:classifier>
        <itsgml:FC_FeatureType gml:id="INSPIRE_TN.FunctionalRoadClass">
            <itsgml:typeName>FunctionalRoadClass</itsgml:typeName>
            <itsgml:isAbstract>false</itsgml:isAbstract>
            <itsgml:inheritsFrom xlink:href="INSPIRE_TN.gml#INSPIRE_TN.TransportProperty" />
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.FunctionalRoadClass.functionalClass">
                    <itsgml:memberName>functionalClass</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>FunctionalRoadClassValue</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
        </itsgml:FC_FeatureType>
    </itsgml:classifier>
    <itsgml:classifier>
        <itsgml:FC_DataType gml:id="INSPIRE_TN.Identifier">
            <itsgml:typeName>Identifier</itsgml:typeName>
            <itsgml:isAbstract>false</itsgml:isAbstract>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.Identifier.localId">
                    <itsgml:memberName>localId</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>CharacterString</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.Identifier.namespace">
                    <itsgml:memberName>namespace</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>CharacterString</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.Identifier.versionId">
                    <itsgml:memberName>versionId</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>0</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>CharacterString</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
        </itsgml:FC_DataType>
    </itsgml:classifier>
    <itsgml:classifier>
        <itsgml:FC_DataType gml:id="INSPIRE_TN.LinkReference">
            <itsgml:typeName>LinkReference</itsgml:typeName>
            <itsgml:isAbstract>false</itsgml:isAbstract>
            <itsgml:inheritsFrom xlink:href="INSPIRE_TN.gml#INSPIRE_TN.NetworkReference" />
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.LinkReference.applicableDirection">
                    <itsgml:memberName>applicableDirection</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>LinkDirectionValue</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
        </itsgml:FC_DataType>
    </itsgml:classifier>
    <itsgml:classifier>
        <itsgml:FC_FeatureType gml:id="INSPIRE_TN.NetworkElement">
            <itsgml:typeName>NetworkElement</itsgml:typeName>
            <itsgml:isAbstract>true</itsgml:isAbstract>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.NetworkElement.beginLifespanVersion">
                    <itsgml:memberName>beginLifespanVersion</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>DateTime</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.NetworkElement.inspireId">
                    <itsgml:memberName>inspireId</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>0</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>Identifier</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.NetworkElement.endLifespanVersion">
                    <itsgml:memberName>endLifespanVersion</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>0</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>DateTime</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
        </itsgml:FC_FeatureType>
    </itsgml:classifier>
    <itsgml:classifier>
        <itsgml:FC_FeatureType gml:id="INSPIRE_TN.NetworkProperty">
            <itsgml:typeName>NetworkProperty</itsgml:typeName>
            <itsgml:isAbstract>true</itsgml:isAbstract>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.NetworkProperty.networkRef">
                    <itsgml:memberName>networkRef</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger isInfinite="true">99999</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>NetworkReference</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.NetworkProperty.inspireId">
                    <itsgml:memberName>inspireId</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>0</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>Identifier</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.NetworkProperty.beginLifespanVersion">
                    <itsgml:memberName>beginLifespanVersion</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>DateTime</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.NetworkProperty.endLifespanVersion">
                    <itsgml:memberName>endLifespanVersion</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>0</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>DateTime</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
        </itsgml:FC_FeatureType>
    </itsgml:classifier>
    <itsgml:classifier>
        <itsgml:FC_DataType gml:id="INSPIRE_TN.NetworkReference">
            <itsgml:typeName>NetworkReference</itsgml:typeName>
            <itsgml:isAbstract>false</itsgml:isAbstract>
        </itsgml:FC_DataType>
    </itsgml:classifier>
    <itsgml:classifier>
        <itsgml:FC_FeatureType gml:id="INSPIRE_TN.RoadWidth">
            <itsgml:typeName>RoadWidth</itsgml:typeName>
            <itsgml:isAbstract>false</itsgml:isAbstract>
            <itsgml:inheritsFrom xlink:href="INSPIRE_TN.gml#INSPIRE_TN.TransportProperty" />
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.RoadWidth.measuredRoadPart">
                    <itsgml:memberName>measuredRoadPart</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>RoadPartValue</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.RoadWidth.width">
                    <itsgml:memberName>width</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>Measure</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
        </itsgml:FC_FeatureType>
    </itsgml:classifier>
    <itsgml:classifier>
        <itsgml:FC_DataType gml:id="INSPIRE_TN.SimpleLinearReference">
            <itsgml:typeName>SimpleLinearReference</itsgml:typeName>
            <itsgml:isAbstract>false</itsgml:isAbstract>
            <itsgml:inheritsFrom xlink:href="INSPIRE_TN.gml#INSPIRE_TN.LinkReference" />
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.SimpleLinearReference.fromPosition">
                    <itsgml:memberName>fromPosition</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>Length</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.SimpleLinearReference.toPosition">
                    <itsgml:memberName>toPosition</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>Length</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.SimpleLinearReference.offset">
                    <itsgml:memberName>offset</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>0</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>Length</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
        </itsgml:FC_DataType>
    </itsgml:classifier>
    <itsgml:classifier>
        <itsgml:FC_DataType gml:id="INSPIRE_TN.SimplePointReference">
            <itsgml:typeName>SimplePointReference</itsgml:typeName>
            <itsgml:isAbstract>false</itsgml:isAbstract>
            <itsgml:inheritsFrom xlink:href="INSPIRE_TN.gml#INSPIRE_TN.LinkReference" />
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.SimplePointReference.atPosition">
                    <itsgml:memberName>atPosition</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>Length</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.SimplePointReference.offset">
                    <itsgml:memberName>offset</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>0</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>Length</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
        </itsgml:FC_DataType>
    </itsgml:classifier>
    <itsgml:classifier>
        <itsgml:FC_FeatureType gml:id="INSPIRE_TN.SpeedLimit">
            <itsgml:typeName>SpeedLimit</itsgml:typeName>
            <itsgml:isAbstract>false</itsgml:isAbstract>
            <itsgml:inheritsFrom xlink:href="INSPIRE_TN.gml#INSPIRE_TN.TransportProperty" />
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.SpeedLimit.areaCondition">
                    <itsgml:memberName>areaCondition</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>0</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>AreaConditionValue</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.SpeedLimit.direction">
                    <itsgml:memberName>direction</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>0</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>LinkDirectionValue</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.SpeedLimit.laneExtension">
                    <itsgml:memberName>laneExtension</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>0</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>Integer</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.SpeedLimit.speedLimitMinMaxType">
                    <itsgml:memberName>speedLimitMinMaxType</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>SpeedLimitMinMaxValue</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.SpeedLimit.speedLimitSource">
                    <itsgml:memberName>speedLimitSource</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>0</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>SpeedLimitSourceValue</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.SpeedLimit.speedLimitValue">
                    <itsgml:memberName>speedLimitValue</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>Velocity</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.SpeedLimit.startLane">
                    <itsgml:memberName>startLane</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>0</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>Integer</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.SpeedLimit.validityPeriod">
                    <itsgml:memberName>validityPeriod</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>0</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>TM_Period</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.SpeedLimit.vehicleType">
                    <itsgml:memberName>vehicleType</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>0</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>VehicleTypeValue</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.SpeedLimit.weatherCondition">
                    <itsgml:memberName>weatherCondition</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>0</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>WeatherConditionValue</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
        </itsgml:FC_FeatureType>
    </itsgml:classifier>
    <itsgml:classifier>
        <itsgml:FC_FeatureType gml:id="INSPIRE_TN.TransportProperty">
            <itsgml:typeName>TransportProperty</itsgml:typeName>
            <itsgml:isAbstract>true</itsgml:isAbstract>
            <itsgml:inheritsFrom xlink:href="INSPIRE_TN.gml#INSPIRE_TN.NetworkProperty" />
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.TransportProperty.validFrom">
                    <itsgml:memberName>validFrom</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>1</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>DateTime</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
            <itsgml:carrierOfCharacteristics>
                <itsgml:FC_FeatureAttribute gml:id="INSPIRE_TN.TransportProperty.validTo">
                    <itsgml:memberName>validTo</itsgml:memberName>
                    <itsgml:cardinality>
                        <gco:Multiplicity>
                            <gco:range>
                                <gco:MultiplicityRange>
                                    <gco:lower>
                                        <gco:Integer>0</gco:Integer>
                                    </gco:lower>
                                    <gco:upper>
                                        <gco:UnlimitedInteger>1</gco:UnlimitedInteger>
                                    </gco:upper>
                                </gco:MultiplicityRange>
                            </gco:range>
                        </gco:Multiplicity>
                    </itsgml:cardinality>
                     <itsgml:valueType>DateTime</itsgml:valueType>
                </itsgml:FC_FeatureAttribute>
            </itsgml:carrierOfCharacteristics>
        </itsgml:FC_FeatureType>
    </itsgml:classifier>
</itsgml:FC_FeatureCatalogue>
